# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PrograssDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtWidgets
from PyQt5.QtCore import QRect, QMetaObject, Qt


class Ui_Form(QtWidgets.QWidget):        

    def setupUi(self):
        self.resize(364, 67)
        self.progressBar = QtWidgets.QProgressBar(self)
        self.progressBar.setGeometry(QRect(10, 30, 341, 23))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(False)
        self.progLabel = QtWidgets.QLabel(self)
        self.progLabel.setGeometry(QRect(10, 10, 341, 16))

        self.retranslateUi()
        QMetaObject.connectSlotsByName(self)

        flags = Qt.WindowFlags(Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint)
        self.setWindowFlags(flags)

    def retranslateUi(self):
        self.setWindowTitle("Form")
        self.progLabel.setText("PrograssText")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
